services:
  # Serviço da aplicação Full-News
  app:
    image: oagara/full-news-maratona:v1
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=fulldevnews
      - DB_USERNAME=fulldevnews
      - DB_PASSWORD=Pg#123
      - DB_SSL_REQUIRE=false
    depends_on:
      - db
    networks:
      - full-news-network

  # Serviço do PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: full-news-db
    environment:
      - POSTGRES_DB=fulldevnews
      - POSTGRES_USER=fulldevnews
      - POSTGRES_PASSWORD=Pg#123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - full-news-network

volumes:
  postgres_data:

networks:
  full-news-network:
    driver: bridge