apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "fulldevnews"
        - name: POSTGRES_USER
          value: "fulldevnews"
        - name: POSTGRES_PASSWORD
          value: "Pg#123"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: full-news-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: full-news-app
  template:
    metadata:
      labels:
        app: full-news-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
      - name: full-news-app
        image: oagara/full-news-maratona:latest
        ports:
        - containerPort: 8080
        env:
        - name: NODE_ENV
          value: "production"
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_PORT
          value: "5432"
        - name: DB_DATABASE
          value: "fulldevnews"
        - name: DB_USERNAME
          value: "fulldevnews"
        - name: DB_PASSWORD
          value: "Pg#123"
        - name: DB_SSL_REQUIRE
          value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: full-news-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: full-news-app